
// This file has been generated by the GUI designer. Do not modify.

using NAudio.Wave;
using System;

public partial class MainWindow
{
	private global::Gtk.Fixed fixed1;

	private global::Gtk.ComboBox combobox1;

	private global::Gtk.Button button2;

	private global::Gtk.Button button5;

	private global::Gtk.Entry entry2;

	private global::Gtk.Button button21;

	private global::Gtk.Button button22;

	private global::Gtk.Button button23;

	private global::Gtk.Button button24;

	private global::Gtk.Button button37;

    private global::Gtk.Button atrasar;

    private global::Gtk.Button adelantar;

    private global::Gtk.Button button38;

    private global::Gtk.Button delete31;

    private global::Gtk.Button delete32;

    private global::Gtk.Button delete33;

    private global::Gtk.Button delete34;

    private global::Gtk.Button edit31;

    private global::Gtk.Button edit32;

    private global::Gtk.Button edit33;

    private global::Gtk.Button edit34;
    private global::Gtk.Button buttonsort;

    private global::Gtk.Image image1;

	private global::Gtk.Label Pagina;

	private global::Gtk.Button button1;

	private global::Gtk.Button button3;

    private global::Gtk.Button lyrics31;

    private global::Gtk.Button lyrics32;

    private global::Gtk.Button lyrics33;

    private global::Gtk.Button lyrics34;


    protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed1 = new global::Gtk.Fixed();
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.combobox1 = global::Gtk.ComboBox.NewText();
		this.combobox1.AppendText(global::Mono.Unix.Catalog.GetString("Cancion"));
		this.combobox1.AppendText(global::Mono.Unix.Catalog.GetString("Letra"));
		this.combobox1.AppendText(global::Mono.Unix.Catalog.GetString("Artista"));
		this.combobox1.AppendText(global::Mono.Unix.Catalog.GetString("Album"));
		this.combobox1.Name = "combobox1";
		this.combobox1.Active = 0;
		this.fixed1.Add(this.combobox1);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.combobox1]));
		w1.X = 800;
		w1.Y = 25;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.button2 = new global::Gtk.Button();
		this.button2.CanFocus = true;
		this.button2.Events = ((global::Gdk.EventMask)(256));
		this.button2.Name = "button2";
		this.button2.UseUnderline = true;
		this.button2.Label = global::Mono.Unix.Catalog.GetString("Agregar Cancion\n");
		this.fixed1.Add(this.button2);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.button2]));
		w2.X = 809;
		w2.Y = 494;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.button5 = new global::Gtk.Button();
		this.button5.CanFocus = true;
		this.button5.Name = "button5";
		this.button5.UseUnderline = true;
		this.button5.Label = global::Mono.Unix.Catalog.GetString("GtkButton");
		this.fixed1.Add(this.button5);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.button5]));
		w3.X = 45;
		w3.Y = 515;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.entry2 = new global::Gtk.Entry();
		this.entry2.CanFocus = true;
		this.entry2.Name = "entry2";
		this.entry2.IsEditable = true;
		this.entry2.InvisibleChar = '●';
		this.fixed1.Add(this.entry2);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.entry2]));
		w4.X = 791;
		w4.Y = 61;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.button21 = new global::Gtk.Button();
		this.button21.WidthRequest = 600;
		this.button21.HeightRequest = 50;
		this.button21.CanFocus = true;
		this.button21.Name = "button21";
		this.button21.UseUnderline = true;
		this.button21.Label = global::Mono.Unix.Catalog.GetString("GtkButton");
		this.fixed1.Add(this.button21);
		global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.button21]));
		w5.X = 90;
		w5.Y = 130;
        // Container child fixed1.Gtk.Fixed+FixedChild
        this.buttonsort = new global::Gtk.Button();
        
        this.buttonsort.CanFocus = true;
        this.buttonsort.Name = "button21";
        this.buttonsort.UseUnderline = true;
        this.buttonsort.Label = global::Mono.Unix.Catalog.GetString("Sort");
        this.fixed1.Add(this.buttonsort);
        global::Gtk.Fixed.FixedChild wsort = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.buttonsort]));
        wsort.X = 900;
        wsort.Y = 25;
        // Container child fixed1.Gtk.Fixed+FixedChild
        this.button22 = new global::Gtk.Button();
		this.button22.WidthRequest = 600;
		this.button22.HeightRequest = 50;
		this.button22.CanFocus = true;
		this.button22.Name = "button22";
		this.button22.UseUnderline = true;
		this.button22.Label = global::Mono.Unix.Catalog.GetString("GtkButton");
		this.fixed1.Add(this.button22);
		global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.button22]));
		w6.X = 90;
		w6.Y = 200;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.button23 = new global::Gtk.Button();
		this.button23.WidthRequest = 600;
		this.button23.HeightRequest = 50;
		this.button23.CanFocus = true;
		this.button23.Name = "button23";
		this.button23.UseUnderline = true;
		this.button23.Label = global::Mono.Unix.Catalog.GetString("GtkButton");
		this.fixed1.Add(this.button23);
		global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.button23]));
		w7.X = 90;
		w7.Y = 270;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.button24 = new global::Gtk.Button();
		this.button24.WidthRequest = 600;
		this.button24.HeightRequest = 50;
		this.button24.CanFocus = true;
		this.button24.Name = "button24";
		this.button24.UseUnderline = true;
		this.button24.Label = global::Mono.Unix.Catalog.GetString("GtkButton");
		this.fixed1.Add(this.button24);
		global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.button24]));
		w8.X = 90;
		w8.Y = 340;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.button37 = new global::Gtk.Button();
		this.button37.CanFocus = true;
		this.button37.Name = "button37";
		this.button37.UseUnderline = true;
		this.button37.Label = global::Mono.Unix.Catalog.GetString("Anterior");
		this.fixed1.Add(this.button37);
		global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.button37]));
		w9.X = 250;
		w9.Y = 500;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.button38 = new global::Gtk.Button();
		this.button38.CanFocus = true;
		this.button38.Name = "button38";
		this.button38.UseUnderline = true;
		this.button38.Label = global::Mono.Unix.Catalog.GetString("Siguiente");
		this.fixed1.Add(this.button38);
		global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.button38]));
		w10.X = 450;
		w10.Y = 500;
        // Container child fixed1.Gtk.Fixed+FixedChild
        this.delete31 = new global::Gtk.Button();
        this.delete31.CanFocus = true;
        this.delete31.Name = "1";
        this.delete31.UseUnderline = true;
        this.delete31.Label = global::Mono.Unix.Catalog.GetString("Delete");
        this.fixed1.Add(this.delete31);
        global::Gtk.Fixed.FixedChild wd31 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.delete31]));
        wd31.X = 700;
        wd31.Y = 140;
        // Container child fixed1.Gtk.Fixed+FixedChild
        this.delete32 = new global::Gtk.Button();
        this.delete32.CanFocus = true;
        this.delete32.Name = "2";
        this.delete32.UseUnderline = true;
        this.delete32.Label = global::Mono.Unix.Catalog.GetString("Delete");
        this.fixed1.Add(this.delete32);
        global::Gtk.Fixed.FixedChild wd32 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.delete32]));
        wd32.X = 700;
        wd32.Y = 210;
        // Container child fixed1.Gtk.Fixed+FixedChild
        this.delete33 = new global::Gtk.Button();
        this.delete33.CanFocus = true;
        this.delete33.Name = "3";
        this.delete33.UseUnderline = true;
        this.delete33.Label = global::Mono.Unix.Catalog.GetString("Delete");
        this.fixed1.Add(this.delete33);
        global::Gtk.Fixed.FixedChild wd33 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.delete33]));
        wd33.X = 700;
        wd33.Y = 280;
        // Container child fixed1.Gtk.Fixed+FixedChild
        this.delete34 = new global::Gtk.Button();
        this.delete34.CanFocus = true;
        this.delete34.Name = "4";
        this.delete34.UseUnderline = true;
        this.delete34.Label = global::Mono.Unix.Catalog.GetString("Delete");
        this.fixed1.Add(this.delete34);
        global::Gtk.Fixed.FixedChild wd34 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.delete34]));
        wd34.X = 700;
        wd34.Y = 340;
        // Container child fixed1.Gtk.Fixed+FixedChild
        this.edit31 = new global::Gtk.Button();
        this.edit31.CanFocus = true;
        this.edit31.Name = "1";
        this.edit31.UseUnderline = true;
        this.edit31.Label = global::Mono.Unix.Catalog.GetString("Edit");
        this.fixed1.Add(this.edit31);
        global::Gtk.Fixed.FixedChild we31 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.edit31]));
        we31.X = 750;
        we31.Y = 140;
        // Container child fixed1.Gtk.Fixed+FixedChild
        this.edit32 = new global::Gtk.Button();
        this.edit32.CanFocus = true;
        this.edit32.Name = "2";
        this.edit32.UseUnderline = true;
        this.edit32.Label = global::Mono.Unix.Catalog.GetString("Edit");
        this.fixed1.Add(this.edit32);
        global::Gtk.Fixed.FixedChild we32 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.edit32]));
        we32.X = 750;
        we32.Y = 210;
        // Container child fixed1.Gtk.Fixed+FixedChild
        this.edit33 = new global::Gtk.Button();
        this.edit33.CanFocus = true;
        this.edit33.Name = "3";
        this.edit33.UseUnderline = true;
        this.edit33.Label = global::Mono.Unix.Catalog.GetString("Edit");
        this.fixed1.Add(this.edit33);
        global::Gtk.Fixed.FixedChild we33 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.edit33]));
        we33.X = 750;
        we33.Y = 280;
        // Container child fixed1.Gtk.Fixed+FixedChild
        this.edit34 = new global::Gtk.Button();
        this.edit34.CanFocus = true;
        this.edit34.Name = "4";
        this.edit34.UseUnderline = true;
        this.edit34.Label = global::Mono.Unix.Catalog.GetString("Edit");
        this.fixed1.Add(this.edit34);
        global::Gtk.Fixed.FixedChild we34 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.edit34]));
        we34.X = 750;
        we34.Y = 340;
        // Container child fixed1.Gtk.Fixed+FixedChild
        this.lyrics31 = new global::Gtk.Button();
        this.lyrics31.CanFocus = true;
        this.lyrics31.Name = "1";
        this.lyrics31.UseUnderline = true;
        this.lyrics31.Label = global::Mono.Unix.Catalog.GetString("Lyrics");
        this.fixed1.Add(this.lyrics31);
        global::Gtk.Fixed.FixedChild wl31 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.lyrics31]));
        wl31.X = 790;
        wl31.Y = 140;
        // Container child fixed1.Gtk.Fixed+FixedChild
        this.lyrics32 = new global::Gtk.Button();
        this.lyrics32.CanFocus = true;
        this.lyrics32.Name = "2";
        this.lyrics32.UseUnderline = true;
        this.lyrics32.Label = global::Mono.Unix.Catalog.GetString("Lyrics");
        this.fixed1.Add(this.lyrics32);
        global::Gtk.Fixed.FixedChild wl32 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.lyrics32]));
        wl32.X = 790;
        wl32.Y = 210;
        // Container child fixed1.Gtk.Fixed+FixedChild
        this.lyrics33 = new global::Gtk.Button();
        this.lyrics33.CanFocus = true;
        this.lyrics33.Name = "3";
        this.lyrics33.UseUnderline = true;
        this.lyrics33.Label = global::Mono.Unix.Catalog.GetString("Lyrics");
        this.fixed1.Add(this.lyrics33);
        global::Gtk.Fixed.FixedChild wl33 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.lyrics33]));
        wl33.X = 790;
        wl33.Y = 280;
        // Container child fixed1.Gtk.Fixed+FixedChild
        this.lyrics34 = new global::Gtk.Button();
        this.lyrics34.CanFocus = true;
        this.lyrics34.Name = "4";
        this.lyrics34.UseUnderline = true;
        this.lyrics34.Label = global::Mono.Unix.Catalog.GetString("Lyrics");
        this.fixed1.Add(this.lyrics34);
        global::Gtk.Fixed.FixedChild wl34 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.lyrics34]));
        wl34.X = 790;
        wl34.Y = 340;

        // Container child fixed1.Gtk.Fixed+FixedChild
        this.Pagina = new global::Gtk.Label();
		this.Pagina.Name = "Pagina";
		this.Pagina.LabelProp = global::Mono.Unix.Catalog.GetString("Numero Pagina");
		this.fixed1.Add(this.Pagina);
		global::Gtk.Fixed.FixedChild w12 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.Pagina]));
		w12.X = 350;
		w12.Y = 505;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.button1 = new global::Gtk.Button();
		this.button1.CanFocus = true;
		this.button1.Name = "button1";
		this.button1.UseStock = true;
		this.button1.UseUnderline = true;
		this.button1.Label = "gtk-media-play";
		this.fixed1.Add(this.button1);
		global::Gtk.Fixed.FixedChild w13 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.button1]));
		w13.X = 317;
		w13.Y = 433;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.button3 = new global::Gtk.Button();
		this.button3.CanFocus = true;
		this.button3.Name = "button3";
		this.button3.UseStock = true;
		this.button3.UseUnderline = true;
		this.button3.Label = "gtk-media-pause";
		this.fixed1.Add(this.button3);
		global::Gtk.Fixed.FixedChild w14 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.button3]));
		w14.X = 414;
		w14.Y = 433;
        //
        this.atrasar = new global::Gtk.Button();
        this.atrasar.CanFocus = true;
        this.atrasar.Name = "button3";
        this.atrasar.UseStock = true;
        this.atrasar.UseUnderline = true;
        this.atrasar.Label = "Atrasar 10s";
        this.fixed1.Add(this.atrasar);
        global::Gtk.Fixed.FixedChild w15 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.atrasar]));
        w15.X = 200;
        w15.Y = 433;
        //atrasar
        this.adelantar = new global::Gtk.Button();
        this.adelantar.CanFocus = true;
        this.adelantar.Name = "button3";
        this.adelantar.UseStock = true;
        this.adelantar.UseUnderline = true;
        this.adelantar.Label = "Adelantar 10s";
        this.fixed1.Add(this.adelantar);
        global::Gtk.Fixed.FixedChild w16 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.adelantar]));
        w16.X = 500;
        w16.Y = 433;
        this.Add(this.fixed1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 988;
		this.DefaultHeight = 575;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
        //this.combobox1.Changed += new global::System.EventHandler(this.SendSort);
        this.entry2.Activated += new global::System.EventHandler(this.SendSort);
		this.button2.Clicked += new global::System.EventHandler(this.OnAgregarCancion);
		this.button5.Clicked += new global::System.EventHandler(this.GetSongs);
		this.button1.Clicked += new global::System.EventHandler(this.Play);
		this.button3.Clicked += new global::System.EventHandler(this.Stop);
        this.button21.Clicked += new global::System.EventHandler(this.PlaySeletedSong);
        this.button22.Clicked += new global::System.EventHandler(this.PlaySeletedSong);
        this.button23.Clicked += new global::System.EventHandler(this.PlaySeletedSong);
        this.button24.Clicked += new global::System.EventHandler(this.PlaySeletedSong);
        this.button37.Clicked += new global::System.EventHandler(this.PreviousPage);
        this.button38.Clicked += new global::System.EventHandler(this.NextPage);
        this.delete31.Clicked += new global::System.EventHandler(this.Delete);
        this.delete32.Clicked += new global::System.EventHandler(this.Delete);
        this.delete33.Clicked += new global::System.EventHandler(this.Delete);
        this.delete34.Clicked += new global::System.EventHandler(this.Delete);
        this.atrasar.Clicked += new global::System.EventHandler(this.Backward);
        this.adelantar.Clicked += new global::System.EventHandler(this.Forward);
        this.buttonsort.Clicked += new global::System.EventHandler(this.SendSort);
        this.edit31.Clicked += new global::System.EventHandler(this.Edit);
        this.edit32.Clicked += new global::System.EventHandler(this.Edit);
        this.edit33.Clicked += new global::System.EventHandler(this.Edit);
        this.edit34.Clicked += new global::System.EventHandler(this.Edit);
        this.lyrics31.Clicked += new global::System.EventHandler(this.ShowLyrics);
        this.lyrics32.Clicked += new global::System.EventHandler(this.ShowLyrics);
        this.lyrics33.Clicked += new global::System.EventHandler(this.ShowLyrics);
        this.lyrics34.Clicked += new global::System.EventHandler(this.ShowLyrics);

        player.PlaybackStopped += new global::System.EventHandler<StoppedEventArgs>(this.ResquestMoreSong);









    }

    
}
