
// This file has been generated by the GUI designer. Do not modify.
namespace OdysseyClient
{
	public partial class AddSongUI
	{
		private global::Gtk.Fixed fixed1;

		private global::Gtk.Label label1;

		private global::Gtk.Entry entry1;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget OdysseyClient.AddSongUI
			this.Name = "OdysseyClient.AddSongUI";
			this.Title = global::Mono.Unix.Catalog.GetString("AddSongUI");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child OdysseyClient.AddSongUI.Gtk.Container+ContainerChild
			this.fixed1 = new global::Gtk.Fixed();
			this.fixed1.Name = "fixed1";
			this.fixed1.HasWindow = false;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label1 = new global::Gtk.Label();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("label1");
			this.fixed1.Add(this.label1);
			global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label1]));
			w1.X = 33;
			w1.Y = 44;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.entry1 = new global::Gtk.Entry();
			this.entry1.CanFocus = true;
			this.entry1.Name = "entry1";
			this.entry1.Text = global::Mono.Unix.Catalog.GetString("Artista");
			this.entry1.IsEditable = true;
			this.entry1.InvisibleChar = '●';
			this.fixed1.Add(this.entry1);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.entry1]));
			w2.X = 78;
			w2.Y = 46;
			this.Add(this.fixed1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show();
		}
	}
}
