
// This file has been generated by the GUI designer. Do not modify.
namespace OdysseyClient
{
	public partial class Login
	{
		private global::Gtk.Fixed fixed4;

		private global::Gtk.Button button2;

		private global::Gtk.Entry entry4;

		private global::Gtk.Entry entry5;

		private global::Gtk.Button button1;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget OdysseyClient.Login
			this.Name = "OdysseyClient.Login";
			this.Title = global::Mono.Unix.Catalog.GetString("Login");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child OdysseyClient.Login.Gtk.Container+ContainerChild
			this.fixed4 = new global::Gtk.Fixed();
			this.fixed4.Name = "fixed4";
			this.fixed4.HasWindow = false;
			// Container child fixed4.Gtk.Fixed+FixedChild
			this.button2 = new global::Gtk.Button();
			this.button2.CanFocus = true;
			this.button2.Name = "button2";
			this.button2.UseUnderline = true;
			this.button2.Label = global::Mono.Unix.Catalog.GetString("Iniciar Sesion");
			this.fixed4.Add(this.button2);
			global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed4[this.button2]));
			w1.X = 130;
			w1.Y = 150;
			// Container child fixed4.Gtk.Fixed+FixedChild
			this.entry4 = new global::Gtk.Entry();
			this.entry4.CanFocus = true;
			this.entry4.Name = "entry4";
			this.entry4.Text = global::Mono.Unix.Catalog.GetString("Usuario");
			this.entry4.IsEditable = true;
			this.entry4.InvisibleChar = '●';
			this.fixed4.Add(this.entry4);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed4[this.entry4]));
			w2.X = 90;
			w2.Y = 70;
			// Container child fixed4.Gtk.Fixed+FixedChild
			this.entry5 = new global::Gtk.Entry();
			this.entry5.CanFocus = true;
			this.entry5.Name = "entry5";
			this.entry5.Text = global::Mono.Unix.Catalog.GetString("Contraseña");
			this.entry5.IsEditable = true;
			this.entry5.Visibility = false;
			this.entry5.InvisibleChar = '●';
			this.fixed4.Add(this.entry5);
			global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed4[this.entry5]));
			w3.X = 90;
			w3.Y = 110;
			// Container child fixed4.Gtk.Fixed+FixedChild
			this.button1 = new global::Gtk.Button();
			this.button1.CanFocus = true;
			this.button1.Name = "button1";
			this.button1.UseUnderline = true;
			this.button1.Label = global::Mono.Unix.Catalog.GetString("Registrarse");
			this.fixed4.Add(this.button1);
			global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed4[this.button1]));
			w4.X = 130;
			w4.Y = 190;
			this.Add(this.fixed4);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 358;
			this.Show();
			this.button2.Clicked += new global::System.EventHandler(this.Access);
			this.button1.Clicked += new global::System.EventHandler(this.Register);
		}
	}
}
